import { Link } from 'react-router-dom'
import { Container } from '../components/layout/SiteChrome'

const areas = [
  ['01', 'Our Educational Platforms', 'Building pathways to authentic Islamic knowledge for learners at every stage.'],
  ['02', "Da'wah & Islamic Outreach", 'Sharing beneficial reminders and creating spaces for meaningful engagement.'],
  ['03', 'Spiritual Development & Tarbiyah', 'Nurturing character, reflection and a living relationship with faith.'],
  ['04', 'Our Members / Community', 'Supporting connection, belonging and the shared work of community wellbeing.'],
  ['05', 'Youth Development & Empowerment', 'Encouraging young people to grow in confidence, purpose and service.'],
  ['06', 'Our Businesses / Community Ecosystem', 'Developing practical initiatives that strengthen people and communities.'],
]

function SectionHeading({ eyebrow, title, children }) {
  return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{children}</div>
}

function Arrow() { return <span aria-hidden="true" className="arrow">↗</span> }

function Home() {
  return <div className="home-page">
    <section className="hero"><div className="hero-pattern" /><Container className="hero-grid"><div className="hero-copy"><div className="identity-chip"><span />Da&apos;wãnã Islamic Foundation <b>•</b> <strong>EST. 1994</strong></div><h1>Knowledge.<br /><em>Faith.</em> Service.<br />Community.</h1><p>Dedicated to authentic Islamic knowledge, Da&apos;wah, spiritual development (Tarbiyah), youth development and community wellbeing.</p><div className="hero-actions"><Link className="button" to="/programs">Explore Our Programs <Arrow /></Link><Link className="button button-outline" to="/about">Learn About Da&apos;wãnã <Arrow /></Link></div><div className="hero-meta"><div><span>Established</span><strong>1994 in Nigeria</strong></div><div><span>Origin</span><strong>The Islamic Front</strong></div><div><span>Watchword</span><strong>Ridwanullahi Akbar</strong></div><div><span>Core Mandate</span><strong>Knowledge &amp; Service</strong></div></div></div><div className="hero-art"><div className="watchword-panel"><div className="panel-pattern" /><div className="panel-top"><span>✦ Foundation watchword</span><b>EST. 1994</b></div><div className="watchword-core"><div className="arabic" lang="ar" dir="rtl">رِضْوَانُ اللهِ أَكْبَرُ</div><p>&quot;Allah&apos;s Pleasure is the greatest&quot;</p></div><div className="panel-bottom"><span>✧</span><div><small>Islamic foundation mandate</small><strong>Grounded in Qur&apos;an, Sunnah &amp; community upliftment</strong></div></div></div></div></Container></section>

    <section className="section who-section" id="who-we-are"><Container className="two-column"><div className="section-intro"><span className="eyebrow">Who we are</span><div className="former-line"><span>Formerly:</span><strong>The Islamic Front</strong></div></div><div className="who-copy"><h2>Building Knowledgeable, Spiritually Grounded and Empowered Communities</h2><p className="lead">Da&apos;wãnã Islamic Foundation is dedicated to the service of Allah and the spiritual, moral, and intellectual development of society. Rooted in authentic Islamic scholarship, we advance sound Islamic learning, structured tarbiyah (spiritual grooming), youth mentorship, and selfless community service.</p><Link className="button button-small" to="/about">About Da&apos;wãnã <Arrow /></Link></div></Container></section>

    <section className="section areas-section" id="what-we-do"><Container><SectionHeading eyebrow="Six foundational areas of intervention" title="What We Do"><p>Our broad institutional mandates shaping long-term educational and societal development.</p></SectionHeading><div className="area-grid">{areas.map(([number, title, copy]) => <article className="area-card" key={title}><span className="card-number">{number}</span><div className="area-icon">✦</div><h3>{title}</h3><p>{copy}</p><a href="#programs">Explore <Arrow /></a></article>)}</div></Container></section>

    <section className="section programs-section" id="programs"><Container><SectionHeading eyebrow="Structured activities & initiatives" title="Ongoing Programs"><Link className="button button-small" to="/programs">Explore Programs <Arrow /></Link></SectionHeading><div className="program-feature"><div className="program-content"><div className="tag-row"><span>Islamic learning</span><span>Regular activity</span></div><h3>Physical Usrah</h3><p>A regular Islamic learning and spiritual development activity. Further program details will be announced as official information becomes available.</p><div className="meta-row"><span>Registration</span><strong>Not required</strong><span>Payment</span><strong>Free</strong></div><Link className="button" to="/programs">Explore Program <Arrow /></Link></div></div></Container></section>

    <section className="projects-section" id="projects"><Container><SectionHeading eyebrow="Strategic initiatives" title="Institutional Projects"><Link className="button button-small" to="/projects">Explore Projects <Arrow /></Link></SectionHeading><div className="project-card"><div><div className="tag-row"><span className="tag-gold">Featured Project Spotlight</span><span>In Development</span></div><h3>Al-Qalam Project</h3><p>An institutional educational and scholarly initiative dedicated to building enduring classical learning infrastructure, digital Islamic knowledge repositories, and scholarly publishing. Designed to foster high-level Islamic intellectual advancement across Nigeria.</p><div className="preview-meta"><span>☷ &nbsp; Classical Learning &amp; Research</span><span>◷ &nbsp; Phased Implementation · Details Coming Soon</span></div></div><Link className="button button-pale" to="/projects">Explore Projects <Arrow /></Link></div></Container></section>

    <section className="dic-band" id="dic"><Container><div><span className="eyebrow gold-eyebrow">Flagship initiative</span><h2>Darul Islam Camp (DIC)</h2><p>An initiative of Da&apos;wãnã Islamic Foundation focused on Islamic learning, spiritual development and community building.</p></div><Link className="button button-gold" to="/dic">Explore DIC <Arrow /></Link></Container></section>

    <section className="section events-section" id="events"><Container><SectionHeading eyebrow="Time-specific gatherings" title="Upcoming Events"><Link className="button button-small" to="/events">View Events <Arrow /></Link></SectionHeading><div className="event-empty"><div className="event-badge"><span>▣</span><strong>MONTHLY</strong></div><div><div className="tag-row"><span className="tag-gold">Recurring Da&apos;wah Activity</span></div><h3>Monthly Da&apos;wah Seminar</h3><p>A recurring Da&apos;wah activity of Da&apos;wãnã Islamic Foundation. Details to be announced.</p></div><Link className="button button-pale" to="/events">View Events <Arrow /></Link></div></Container></section>

    <section className="section media-section" id="media"><Container><SectionHeading eyebrow="Knowledge library" title="Learn. Listen. Watch."><Link className="button button-small" to="/media">Explore Media <Arrow /></Link></SectionHeading><div className="media-feature"><div className="tag-row"><span>Featured Audio Treatise</span><span className="tag-gold">54 Minutes · Scholarly Archive</span></div><h3>Foundations of Islamic Tarbiyah in the Contemporary Age</h3><p>An in-depth exposition on preserving spiritual sincerity, ethical fortitude, and wholesome family devotion amidst modern societal distractions. Available as high-fidelity audio stream and downloadable reference notes.</p><div className="preview-meta"><span>◉ &nbsp; Audio Lecture &amp; Syllabus</span><span>⇩ &nbsp; Study Text Available</span></div></div></Container></section>

    <section className="impact-band"><Container><span className="eyebrow gold-eyebrow">Impact / community</span><h2>Knowledge That Transforms.<br /><em>Service That Matters.</em></h2><p>When beneficial knowledge is shared and lived, it becomes a source of strength for individuals, families and communities.</p></Container></section>

    <section className="section involved-section" id="get-involved"><Container><SectionHeading eyebrow="Participate in the mission" title="Get Involved With Da&apos;wãnã"><Link className="button button-small" to="/get-involved">Get Involved <Arrow /></Link></SectionHeading><p className="section-copy">Every individual has talents, sincere effort, and resources to contribute toward elevating our communities. Join us across educational circles, scholarly partnerships, welfare operations, and community fellowship.</p></Container></section>

    <section className="donate-section" id="donate"><Container><div className="donate-card"><div className="donate-copy"><span className="eyebrow gold-eyebrow">Continuous charity (Sadaqah Jariyah)</span><h2>Support Beneficial Knowledge and Community Development</h2><p>Your voluntary contributions sustain authentic Islamic learning circles, regular spiritual gatherings, Darul Islam Camp, youth programs, and community welfare initiatives across Nigeria.</p><div className="donate-assurances"><span>♙ &nbsp; Secure Payment Processing</span><span>♢ &nbsp; Transparent Institutional Stewardship</span></div></div><div className="donate-box"><label>Support frequency</label><div className="frequency-toggle"><button type="button">One-Time Gift</button><button type="button">Monthly Support</button></div><label htmlFor="cause-select">Designate contribution</label><select id="cause-select" defaultValue="general"><option value="general">General Support</option><option value="education">Islamic Education &amp; Usrah</option><option value="dic">Darul Islam Camp (DIC)</option></select><label>Select amount (NGN)</label><div className="amount-options"><button type="button">₦5,000</button><button className="selected" type="button">₦10,000</button><button type="button">₦25,000</button><button type="button">₦50,000</button></div><label htmlFor="custom-amount">Or custom amount</label><input id="custom-amount" className="custom-amount" placeholder="₦  Enter amount in Naira" inputMode="numeric" /><button className="button" type="button">♙ &nbsp; Donate ₦10,000</button><small>♢ &nbsp; Secure payment · Your information is protected</small></div></div></Container></section>
    <section className="newsletter"><Container><div><span className="eyebrow">Stay connected</span><h2>Stay Connected With Da&apos;wãnã</h2><p>Receive updates about programs, events, Islamic educational content and Da&apos;wãnã initiatives.</p></div><form onSubmit={(event) => event.preventDefault()}><label className="sr-only" htmlFor="email">Email address</label><input id="email" type="email" placeholder="Your email address" required /><button className="button" type="submit">Subscribe <Arrow /></button></form></Container></section>
  </div>
}

export default Home
